# Generated by Django 4.2.7 on 2023-12-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_name', models.CharField(max_length=20)),
                ('image_url_mark', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=20)),
                ('image_url_model', models.ImageField(upload_to='')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppParts.marks')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppParts.categories')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('image_url_part', models.ImageField(height_field=200, upload_to='part_media', width_field=200)),
                ('availability', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('model', models.ManyToManyField(to='AppParts.models')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppParts.categories')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='model',
            field=models.ManyToManyField(to='AppParts.marks'),
        ),
    ]
