# Generated by Django 4.2.7 on 2023-12-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppParts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppParts.subcategories'),
        ),
    ]
