# Generated by Django 4.2.7 on 2023-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParts', '0004_parts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='additional_image_one',
            field=models.ImageField(blank=True, null=True, upload_to='part_media'),
        ),
        migrations.AddField(
            model_name='parts',
            name='additional_image_three',
            field=models.ImageField(blank=True, null=True, upload_to='part_media'),
        ),
        migrations.AddField(
            model_name='parts',
            name='additional_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='part_media'),
        ),
    ]
