# Generated by Django 4.2.7 on 2023-12-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppParts', '0005_parts_additional_image_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disassembly',
            fields=[
                ('disassembly_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('image_url_part', models.ImageField(upload_to='disassembly_media')),
                ('additional_image_one', models.ImageField(blank=True, null=True, upload_to='disassembly_media')),
                ('additional_image_two', models.ImageField(blank=True, null=True, upload_to='disassembly_media')),
                ('additional_image_three', models.ImageField(blank=True, null=True, upload_to='disassembly_media')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppParts.marks')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppParts.models')),
            ],
            options={
                'verbose_name': 'Disassembly',
                'verbose_name_plural': 'Disassembly',
            },
        ),
    ]
