# Generated by Django 4.2.7 on 2023-12-29 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParts', '0006_disassembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='disassembly',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
